(cl:in-package novatel_pkg-msg)
(cl:export '(HEADER-VAL
          HEADER
          SOL_STAT-VAL
          SOL_STAT
          POS_TYPE-VAL
          POS_TYPE
          LAT-VAL
          LAT
          LON-VAL
          LON
          HGT-VAL
          HGT
          UNDULATION-VAL
          UNDULATION
          DATUM_ID-VAL
          DATUM_ID
          LAT_STD-VAL
          LAT_STD
          LONG_STD-VAL
          LONG_STD
          HGT_STD-VAL
          HGT_STD
          STN_ID-VAL
          STN_ID
          DIFF_AGE-VAL
          DIFF_AGE
          SOL_AGE-VAL
          SOL_AGE
          NUM_SATS-VAL
          NUM_SATS
          NUM_SOL_SATS-VAL
          NUM_SOL_SATS
          NUM_SOL_L1_SATS-VAL
          NUM_SOL_L1_SATS
          NUM_SOL_MULTI_SATS-VAL
          NUM_SOL_MULTI_SATS
))