# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from novatel_pkg/CommonLongHeader.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CommonLongHeader(genpy.Message):
  _md5sum = "3f5766af824e367c70c99b070c50ec08"
  _type = "novatel_pkg/CommonLongHeader"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Long Binary Header NovAtel
# Author: Brandon Medellin
# Date: 2/1/2023

# Length of the header
uint8 head_length

# Message ID of the log being output
uint16 id

# Measurement source, format, response bit.
uint8 msg_type

# Port address
uint8 port_addr

# Message length not including header (25 bytes) nor CRC (4 bytes)
uint16 length

# Used for multiple related logs. It is a number that counts down from N-1 to 0 where N is the number of related logs ...
uint16 sequence

# Time the processor is idle, calculated once per second - more in documentation
uint8 idle_time

# Indicates the quality of the gps reference time
uint8 time_status

# GNSS week number
uint16 gnss_week

# GNSS Miliseconds from beginning of GNSS week
int32 gnss_mili

# Reserved for internal use
uint16 reserved

# A value (0-65535) representing the receiver software build number
uint16 software_version

"""
  __slots__ = ['head_length','id','msg_type','port_addr','length','sequence','idle_time','time_status','gnss_week','gnss_mili','reserved','software_version']
  _slot_types = ['uint8','uint16','uint8','uint8','uint16','uint16','uint8','uint8','uint16','int32','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       head_length,id,msg_type,port_addr,length,sequence,idle_time,time_status,gnss_week,gnss_mili,reserved,software_version

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CommonLongHeader, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.head_length is None:
        self.head_length = 0
      if self.id is None:
        self.id = 0
      if self.msg_type is None:
        self.msg_type = 0
      if self.port_addr is None:
        self.port_addr = 0
      if self.length is None:
        self.length = 0
      if self.sequence is None:
        self.sequence = 0
      if self.idle_time is None:
        self.idle_time = 0
      if self.time_status is None:
        self.time_status = 0
      if self.gnss_week is None:
        self.gnss_week = 0
      if self.gnss_mili is None:
        self.gnss_mili = 0
      if self.reserved is None:
        self.reserved = 0
      if self.software_version is None:
        self.software_version = 0
    else:
      self.head_length = 0
      self.id = 0
      self.msg_type = 0
      self.port_addr = 0
      self.length = 0
      self.sequence = 0
      self.idle_time = 0
      self.time_status = 0
      self.gnss_week = 0
      self.gnss_mili = 0
      self.reserved = 0
      self.software_version = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BH2B2H2BHi2H().pack(_x.head_length, _x.id, _x.msg_type, _x.port_addr, _x.length, _x.sequence, _x.idle_time, _x.time_status, _x.gnss_week, _x.gnss_mili, _x.reserved, _x.software_version))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.head_length, _x.id, _x.msg_type, _x.port_addr, _x.length, _x.sequence, _x.idle_time, _x.time_status, _x.gnss_week, _x.gnss_mili, _x.reserved, _x.software_version,) = _get_struct_BH2B2H2BHi2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BH2B2H2BHi2H().pack(_x.head_length, _x.id, _x.msg_type, _x.port_addr, _x.length, _x.sequence, _x.idle_time, _x.time_status, _x.gnss_week, _x.gnss_mili, _x.reserved, _x.software_version))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.head_length, _x.id, _x.msg_type, _x.port_addr, _x.length, _x.sequence, _x.idle_time, _x.time_status, _x.gnss_week, _x.gnss_mili, _x.reserved, _x.software_version,) = _get_struct_BH2B2H2BHi2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BH2B2H2BHi2H = None
def _get_struct_BH2B2H2BHi2H():
    global _struct_BH2B2H2BHi2H
    if _struct_BH2B2H2BHi2H is None:
        _struct_BH2B2H2BHi2H = struct.Struct("<BH2B2H2BHi2H")
    return _struct_BH2B2H2BHi2H
