# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from novatel_pkg/CommonShortHeader.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CommonShortHeader(genpy.Message):
  _md5sum = "24bd93da6a66ad1feeb30cf4cc10f233"
  _type = "novatel_pkg/CommonShortHeader"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Short Binary Header NovAtel OEM7
# Author: Brandon Medellin
# Date: 2/1/2023

# Message Length not including header (12 bytes) or CRC (4 byte)
uint8 length

# Message ID of the log being output.
uint16 id

# GNSS week number
uint16 gnss_week

# GNSS Miliseconds from beginning of GNSS week
int32 gnss_mili
"""
  __slots__ = ['length','id','gnss_week','gnss_mili']
  _slot_types = ['uint8','uint16','uint16','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       length,id,gnss_week,gnss_mili

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CommonShortHeader, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.length is None:
        self.length = 0
      if self.id is None:
        self.id = 0
      if self.gnss_week is None:
        self.gnss_week = 0
      if self.gnss_mili is None:
        self.gnss_mili = 0
    else:
      self.length = 0
      self.id = 0
      self.gnss_week = 0
      self.gnss_mili = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2Hi().pack(_x.length, _x.id, _x.gnss_week, _x.gnss_mili))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.length, _x.id, _x.gnss_week, _x.gnss_mili,) = _get_struct_B2Hi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2Hi().pack(_x.length, _x.id, _x.gnss_week, _x.gnss_mili))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.length, _x.id, _x.gnss_week, _x.gnss_mili,) = _get_struct_B2Hi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2Hi = None
def _get_struct_B2Hi():
    global _struct_B2Hi
    if _struct_B2Hi is None:
        _struct_B2Hi = struct.Struct("<B2Hi")
    return _struct_B2Hi
