# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ars_40X/Object.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Object(genpy.Message):
  _md5sum = "8964eb9576b0dc02d837314dcf39da9a"
  _type = "ars_40X/Object"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 id

geometry_msgs/PoseWithCovariance position
geometry_msgs/TwistWithCovariance relative_velocity
geometry_msgs/AccelWithCovariance relative_acceleration

float32 length
float32 width
float32 orientation_angle

float32 rcs
int8 dynamic_property
int8 class_type
int8 meas_state
int8 prob_of_exist
================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertainty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/AccelWithCovariance
# This expresses acceleration in free space with uncertainty.

Accel accel

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
"""
  __slots__ = ['id','position','relative_velocity','relative_acceleration','length','width','orientation_angle','rcs','dynamic_property','class_type','meas_state','prob_of_exist']
  _slot_types = ['uint8','geometry_msgs/PoseWithCovariance','geometry_msgs/TwistWithCovariance','geometry_msgs/AccelWithCovariance','float32','float32','float32','float32','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,position,relative_velocity,relative_acceleration,length,width,orientation_angle,rcs,dynamic_property,class_type,meas_state,prob_of_exist

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Object, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.position is None:
        self.position = geometry_msgs.msg.PoseWithCovariance()
      if self.relative_velocity is None:
        self.relative_velocity = geometry_msgs.msg.TwistWithCovariance()
      if self.relative_acceleration is None:
        self.relative_acceleration = geometry_msgs.msg.AccelWithCovariance()
      if self.length is None:
        self.length = 0.
      if self.width is None:
        self.width = 0.
      if self.orientation_angle is None:
        self.orientation_angle = 0.
      if self.rcs is None:
        self.rcs = 0.
      if self.dynamic_property is None:
        self.dynamic_property = 0
      if self.class_type is None:
        self.class_type = 0
      if self.meas_state is None:
        self.meas_state = 0
      if self.prob_of_exist is None:
        self.prob_of_exist = 0
    else:
      self.id = 0
      self.position = geometry_msgs.msg.PoseWithCovariance()
      self.relative_velocity = geometry_msgs.msg.TwistWithCovariance()
      self.relative_acceleration = geometry_msgs.msg.AccelWithCovariance()
      self.length = 0.
      self.width = 0.
      self.orientation_angle = 0.
      self.rcs = 0.
      self.dynamic_property = 0
      self.class_type = 0
      self.meas_state = 0
      self.prob_of_exist = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B7d().pack(_x.id, _x.position.pose.position.x, _x.position.pose.position.y, _x.position.pose.position.z, _x.position.pose.orientation.x, _x.position.pose.orientation.y, _x.position.pose.orientation.z, _x.position.pose.orientation.w))
      buff.write(_get_struct_36d().pack(*self.position.covariance))
      _x = self
      buff.write(_get_struct_6d().pack(_x.relative_velocity.twist.linear.x, _x.relative_velocity.twist.linear.y, _x.relative_velocity.twist.linear.z, _x.relative_velocity.twist.angular.x, _x.relative_velocity.twist.angular.y, _x.relative_velocity.twist.angular.z))
      buff.write(_get_struct_36d().pack(*self.relative_velocity.covariance))
      _x = self
      buff.write(_get_struct_6d().pack(_x.relative_acceleration.accel.linear.x, _x.relative_acceleration.accel.linear.y, _x.relative_acceleration.accel.linear.z, _x.relative_acceleration.accel.angular.x, _x.relative_acceleration.accel.angular.y, _x.relative_acceleration.accel.angular.z))
      buff.write(_get_struct_36d().pack(*self.relative_acceleration.covariance))
      _x = self
      buff.write(_get_struct_4f4b().pack(_x.length, _x.width, _x.orientation_angle, _x.rcs, _x.dynamic_property, _x.class_type, _x.meas_state, _x.prob_of_exist))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.PoseWithCovariance()
      if self.relative_velocity is None:
        self.relative_velocity = geometry_msgs.msg.TwistWithCovariance()
      if self.relative_acceleration is None:
        self.relative_acceleration = geometry_msgs.msg.AccelWithCovariance()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.id, _x.position.pose.position.x, _x.position.pose.position.y, _x.position.pose.position.z, _x.position.pose.orientation.x, _x.position.pose.orientation.y, _x.position.pose.orientation.z, _x.position.pose.orientation.w,) = _get_struct_B7d().unpack(str[start:end])
      start = end
      end += 288
      self.position.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.relative_velocity.twist.linear.x, _x.relative_velocity.twist.linear.y, _x.relative_velocity.twist.linear.z, _x.relative_velocity.twist.angular.x, _x.relative_velocity.twist.angular.y, _x.relative_velocity.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.relative_velocity.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.relative_acceleration.accel.linear.x, _x.relative_acceleration.accel.linear.y, _x.relative_acceleration.accel.linear.z, _x.relative_acceleration.accel.angular.x, _x.relative_acceleration.accel.angular.y, _x.relative_acceleration.accel.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.relative_acceleration.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 20
      (_x.length, _x.width, _x.orientation_angle, _x.rcs, _x.dynamic_property, _x.class_type, _x.meas_state, _x.prob_of_exist,) = _get_struct_4f4b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B7d().pack(_x.id, _x.position.pose.position.x, _x.position.pose.position.y, _x.position.pose.position.z, _x.position.pose.orientation.x, _x.position.pose.orientation.y, _x.position.pose.orientation.z, _x.position.pose.orientation.w))
      buff.write(self.position.covariance.tostring())
      _x = self
      buff.write(_get_struct_6d().pack(_x.relative_velocity.twist.linear.x, _x.relative_velocity.twist.linear.y, _x.relative_velocity.twist.linear.z, _x.relative_velocity.twist.angular.x, _x.relative_velocity.twist.angular.y, _x.relative_velocity.twist.angular.z))
      buff.write(self.relative_velocity.covariance.tostring())
      _x = self
      buff.write(_get_struct_6d().pack(_x.relative_acceleration.accel.linear.x, _x.relative_acceleration.accel.linear.y, _x.relative_acceleration.accel.linear.z, _x.relative_acceleration.accel.angular.x, _x.relative_acceleration.accel.angular.y, _x.relative_acceleration.accel.angular.z))
      buff.write(self.relative_acceleration.covariance.tostring())
      _x = self
      buff.write(_get_struct_4f4b().pack(_x.length, _x.width, _x.orientation_angle, _x.rcs, _x.dynamic_property, _x.class_type, _x.meas_state, _x.prob_of_exist))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.PoseWithCovariance()
      if self.relative_velocity is None:
        self.relative_velocity = geometry_msgs.msg.TwistWithCovariance()
      if self.relative_acceleration is None:
        self.relative_acceleration = geometry_msgs.msg.AccelWithCovariance()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.id, _x.position.pose.position.x, _x.position.pose.position.y, _x.position.pose.position.z, _x.position.pose.orientation.x, _x.position.pose.orientation.y, _x.position.pose.orientation.z, _x.position.pose.orientation.w,) = _get_struct_B7d().unpack(str[start:end])
      start = end
      end += 288
      self.position.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.relative_velocity.twist.linear.x, _x.relative_velocity.twist.linear.y, _x.relative_velocity.twist.linear.z, _x.relative_velocity.twist.angular.x, _x.relative_velocity.twist.angular.y, _x.relative_velocity.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.relative_velocity.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.relative_acceleration.accel.linear.x, _x.relative_acceleration.accel.linear.y, _x.relative_acceleration.accel.linear.z, _x.relative_acceleration.accel.angular.x, _x.relative_acceleration.accel.angular.y, _x.relative_acceleration.accel.angular.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 288
      self.relative_acceleration.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 20
      (_x.length, _x.width, _x.orientation_angle, _x.rcs, _x.dynamic_property, _x.class_type, _x.meas_state, _x.prob_of_exist,) = _get_struct_4f4b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_4f4b = None
def _get_struct_4f4b():
    global _struct_4f4b
    if _struct_4f4b is None:
        _struct_4f4b = struct.Struct("<4f4b")
    return _struct_4f4b
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_B7d = None
def _get_struct_B7d():
    global _struct_B7d
    if _struct_B7d is None:
        _struct_B7d = struct.Struct("<B7d")
    return _struct_B7d
