# TIME Message ID: 101
# Author: Brandon Medellin
# Date: 3/21/2023

novatel_pkg/CommonLongHeader header

# Clock Model Status
uint32 clock_status

# Receiver clock offset in seconds from GPS system time
float64 offset

# Receiver clock offset standard deviation
float64 offset_std

# The offset of GPS system time from UTC time
float64 utc_offset

# UTC year
uint32 utc_year

# UTC Month (0-12)
uint8 utc_month

# UTC Day (0-31)
uint8 utc_year

# UTC hour (0-23)
uint8 utc_hour

# UTC min (0-59)
uint8 utc_min

# UTC millisecond (0-60999)
uint32 utc_ms

# UTC status (0: invalid, 1: valid, 2: warning)
uint32 utc_status